### ISSUE TITLE
Password on the user-agent

### ISSUE THREAD

**Issue by gkbrk** [WatchPeopleCode/SideBar-Bot#8]
Hey there!
[This line](https://github.com/WatchPeopleCode/SideBar-Bot/blob/master/bot.py#L28) doesn't look right. It sends the password in the user-agent. I think you meant

```
self.r = Reddit("{0} a bot for /r/{1} to set top WPC streams!".format(self._username, self._subreddit))
```

**Comment by paked** [comment]
Yeah that definitely doesn't look right! Thanks for the catch!
